config {
    type: "table",
    description: "Last release date of each service with distance from today"
}

SELECT
  DISTINCT(product_name),
  FIRST_VALUE(published_at) OVER (PARTITION BY product_name ORDER BY published_at DESC) AS last_release_date,
  DATE_DIFF(CURRENT_DATE(),FIRST_VALUE(published_at) OVER (PARTITION BY product_name ORDER BY published_at DESC), DAY) AS days_since_last_release
FROM
  ${ref("rationalize_product_name")}
ORDER BY
  days_since_last_release DESC
